### ISSUE TITLE
Docker hub repository 중 프로젝트 정보가 없는 저장소 목록

### ISSUE THREAD

**Issue by yeonhee-ryou** [prosyslab/bug-bench#31]
버전 태그에 patch 가 들어가고 프로젝트 명에 버전정보가 들어간 경우입니다.
https://hub.docker.com/repository/docker/prosyslab/bug-bench-2.0a/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-2.1.1/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-5.4.2/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-0.9.62/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-20190722/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-1.2.14/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-0.49.4/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-0.5.3/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-2.36.11/tags
https://hub.docker.com/repository/docker/prosyslab/bug-bench-1.1.14/tags

# 해결
1. 위와 같은 잘못된 이름으로 이미지를 빌드하지 않도록 디렉토리 구조를 수정했습니다: 36e3210
2. 원래의 프로젝트를 찾아서 원본 프로젝트에 태그로 백업해두었습니다
예시: https://hub.docker.com/repository/docker/prosyslab/bug-bench-picocom/tags

# 할일
위에 잘못 생성된 저장소 확인하여 삭제

**Comment by KihongHeo** [comment]
@yeonhee-ryou 위 내용 아직도 해결이 안된건가? 그렇다면 이번주안에 해결 부탁한다.

**Comment by yeonhee-ryou** [comment]
@goodtaeeun 위 도커 저장소 지워도 괜찮으면 저장소 모두 지우고 이 이슈 닫겠습니다

**Comment by goodtaeeun** [comment]
네, 괜찮을 것 같습니다.

**Comment by goodtaeeun** [comment]
삭제 완료했습니다.
