### ISSUE TITLE
flvmeta 정리

### ISSUE THREAD

**Issue by KihongHeo** [prosyslab/bug-bench#44]
- [x] CVE 항목 이상함. "issue-13"? 제대로된 CVE 번호로
- [ ] 오류 경로 추가

**Comment by Re-st** [comment]
issue-13의 경우 CVE가 부여되지 않은 issue report([링크](https://github.com/noirotm/flvmeta/issues/13))입니다. label.json에 추가한 이유는 우리 연구에 사용하는 벤치마크로 추가해서 그렇습니다. 제거하는 게 좋을까요, 아니면 이름을 잘 붙이는 게 좋을까요?

**Comment by Re-st** [comment]
https://github.com/prosyslab/bug-bench/commit/fa522fc8912d8d38b70bb59aad85697717d6a43a 에서 업데이트했습니다.
