### ISSUE TITLE
zabbix

### ISSUE THREAD

**Issue by KihongHeo** [prosyslab/bug-bench#47]
오류 경로 넣고 haechi 에서 검출되도록 변경

**Comment by leehahoon** [comment]
#54 PR을 통해서 zabbix의 오류 경로(trace)를 추가했습니다.
단, 해당 오류의 경우, command-injection 취약점으로 기존 haechi에서는 탐지하지 않는 오류 종류입니다.
오류 경로만 추가하도록 할까요?

**Comment by KihongHeo** [comment]
haechi 에 cmd injection checker 추가해서 이제 검출이 된다.
