### ISSUE TITLE
libsndfile

### ISSUE THREAD

**Issue by KihongHeo** [prosyslab/bug-bench#50]
현재 들어있는 c 파일과 ll 파일에는 main 함수가 없음.
[버그 리포트](https://blogs.gentoo.org/ago/2017/04/29/libsndfile-global-buffer-overflow-in-i2les_array-pcm-c/)에 보면 해당 라이브러리를 쓰는 sndfile-convert.c 의 main 에서부터 시작하는 응용프로그램이 있음. 그걸로 분석이 되게끔 변경.

**Comment by Re-st** [comment]
[이 커밋](https://github.com/prosyslab/bug-bench/commit/7992b5447fca599df8fce0e70f762bf59ed1721c)에서 업데이트했습니다. 함수 호출 스택의 모든 함수들이 등장하는 것을 확인했습니다.

**Comment by KihongHeo** [comment]
분석 결과 검출이 잘되네. 수고했다.
